# Add AVT name and labels below
---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
 name: <AVT_NAME> 
spec:
 affinity:
   clusterAffinity:
     clusterSelectorTerms:
       - matchExpressions:
           - key: tmc.cloud.vmware.com/creator
             operator: In
             values:
               - <VALUE>
           - key: location
             operator: In
             values:
               - <VALUE>
           - key: owner
             operator: In
             values:
               - <VALUE>
   clusterAntiAffinity:
     clusterSelectorTerms: []
