---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
 name: zalam-avt-1
spec:
 affinity:
   clusterAffinity:
     clusterSelectorTerms:
       - matchExpressions:
           - key: tmc.cloud.vmware.com/creator
             operator: In
             values:
               - zalam
           - key: location
             operator: In
             values:
               - ireland
           - key: owner
             operator: In
             values:
               - zahoor
   clusterAntiAffinity:
     clusterSelectorTerms: []
